### ISSUE TITLE
Using memcpy instead of memcpy32 in sample?

### ISSUE THREAD

**Issue by Guriido** [gbadev-org/libtonc-template#3]
Minor details considering the purpose of this code, but as the image conversion with grit generates metrTilesLen and metrPalLen in bytes unit, it may be better to use the values using memcpy?

https://github.com/gbadev-org/libtonc-template/blob/a1a5ecfe34ea58b3803a40b1af3067fb78c2d4d9/source/main.c#L12

The division by four comes from nowhere, so if memcpy32 seems preferable, a short comment explaining that we know what we are doing could be welcome.

(I wondered for some time why does the division by 4 allows to copy the whole data, before realizing that it was not memcpy function...)

**Comment by AntonioND** [comment]
The reason for this is that VRAM can only be written in units of 16 or 32 bit. Regular `memcpy` doesn't guarantee the width of the writes, while `memcpy32` does.

We can add a comment, yeah.

**Comment by AntonioND** [comment]
Comment added here: https://github.com/gbadev-org/libtonc-template/commit/90f957279a53fdcf253984b0a3e347e7068ba3ac
